# Custom Language File for Launcher Customizer

[ejs.app]
title = "NF Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/najoan125/NF-Launcher"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "http://discord.hyfata.kr/"

[ejs.settings]
sourceGithubLink = "https://github.com/najoan125/NF-Launcher"
supportLink = "https://github.com/najoan125/NF-Launcher/issues"

[ejs.welcome]
welcomeHeader = "NF Client"
welcomeDescription = "NF Client는 Najoan's Fabric Client의 약자로, Najoan이 만든 Fabric 모드팩 클라이언트라는 의미를 갖고 있습니다. NF Client의 목표는 최대한 많은 기능들을 바닐라에 의존하고, 인게임에 영향을 미치지 않으면서 사용자에게 편리함을 제공하는 것입니다."
welcomeDescCTA = "바닐라 버전과 이질감이 들지 않는 최고의 클라이언트를 계속해서 만들겠습니다."
